CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE m_user (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp without time zone NOT NULL,
    create_user character varying(128),
    create_program character varying(128) NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    update_user character varying(128),
    update_program character varying(128) NOT NULL,
    CONSTRAINT "PK_m_user" PRIMARY KEY (id)
);
COMMENT ON TABLE m_user IS 'ユーザマスタ';
COMMENT ON COLUMN m_user.id IS 'ユーザマスタID:【値例】1';
COMMENT ON COLUMN m_user.name IS '名称:【値例】管理者';
COMMENT ON COLUMN m_user.is_deleted IS '論理削除:【値例】false：未削除 , true：削除済み';
COMMENT ON COLUMN m_user.created_at IS '作成日時:【値例】2025/04/09 10:00:00';
COMMENT ON COLUMN m_user.create_user IS '作成者:【値例】System';
COMMENT ON COLUMN m_user.create_program IS '作成プログラム:【値例】System';
COMMENT ON COLUMN m_user.updated_at IS '更新日時:【値例】2025/04/09 10:00:00';
COMMENT ON COLUMN m_user.update_user IS '更新者:【値例】System';
COMMENT ON COLUMN m_user.update_program IS '更新プログラム:【値例】System';

CREATE TABLE s_email_address_domain (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    domain character varying(128) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT FALSE,
    created_at timestamp without time zone NOT NULL,
    create_user character varying(128),
    create_program character varying(128) NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    update_user character varying(128),
    update_program character varying(128) NOT NULL,
    CONSTRAINT "PK_s_email_address_domain" PRIMARY KEY (id)
);
COMMENT ON TABLE s_email_address_domain IS 'メールアドレスドメインシステムテーブル';
COMMENT ON COLUMN s_email_address_domain.id IS 'ドメインID:【値例】1';
COMMENT ON COLUMN s_email_address_domain.domain IS 'ドメイン:【値例】管理者';
COMMENT ON COLUMN s_email_address_domain.is_deleted IS '論理削除:【値例】false：未削除 , true：削除済み';
COMMENT ON COLUMN s_email_address_domain.created_at IS '作成日時:【値例】2025/04/09 10:00:00';
COMMENT ON COLUMN s_email_address_domain.create_user IS '作成者:【値例】System';
COMMENT ON COLUMN s_email_address_domain.create_program IS '作成プログラム:【値例】System';
COMMENT ON COLUMN s_email_address_domain.updated_at IS '更新日時:【値例】2025/04/09 10:00:00';
COMMENT ON COLUMN s_email_address_domain.update_user IS '更新者:【値例】System';
COMMENT ON COLUMN s_email_address_domain.update_program IS '更新プログラム:【値例】System';

CREATE TABLE t_user (
    id bigserial NOT NULL,
    m_user_id integer NOT NULL,
    last_name character varying(128) NOT NULL,
    email_address character varying(128) NOT NULL,
    s_email_address_domain_id integer NOT NULL,
    first_name character varying(128) NOT NULL,
    created_at timestamp without time zone NOT NULL,
    create_user character varying(128),
    create_program character varying(128) NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    update_user character varying(128),
    update_program character varying(128) NOT NULL,
    CONSTRAINT "PK_t_user" PRIMARY KEY (id)
);
COMMENT ON TABLE t_user IS 'ユーザテーブル';
COMMENT ON COLUMN t_user.id IS 'ユーザID:【値例】1';
COMMENT ON COLUMN t_user.m_user_id IS 'ユーザマスタID:【値例】1';
COMMENT ON COLUMN t_user.last_name IS '姓:【値例】伊藤';
COMMENT ON COLUMN t_user.email_address IS 'メールアドレス:【値例】abcdefg';
COMMENT ON COLUMN t_user.s_email_address_domain_id IS 'メールアドレスドメインID:【値例】1';
COMMENT ON COLUMN t_user.first_name IS '名:【値例】太郎';
COMMENT ON COLUMN t_user.created_at IS '作成日時:【値例】2025/04/09 10:00:00';
COMMENT ON COLUMN t_user.create_user IS '作成者:【値例】System';
COMMENT ON COLUMN t_user.create_program IS '作成プログラム:【値例】System';
COMMENT ON COLUMN t_user.updated_at IS '更新日時:【値例】2025/04/09 10:00:00';
COMMENT ON COLUMN t_user.update_user IS '更新者:【値例】System';
COMMENT ON COLUMN t_user.update_program IS '更新プログラム:【値例】System';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250409145126_InitializeCreated', '9.0.4');

COMMIT;

